name: workflowcallTest
on:
  workflow_dispatch:
    inputs:
      log_level:
        type: choice
        description: "Renovate log level (DEBUG, INFO, WARN, ERROR, FATAL)"
        options:
        - "DEBUG"
        - "INFO"
        - "WARN"
        - "ERROR"
        - "FATAL"
        default: "INFO"
        required: false
    secrets:
      token:
        description: "RENOVATEBOT Token"
        required: true

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  renovate:
    uses: maheshkhade/workflows/.github/workflows/renovate.yaml@main
    with:
      renovate_log_level: ${{ github.event.inputs.log_level }}
    secrets:
      token: ${{ secrets.RENOVATE_TOKEN }}  #  Passing the token